terms = ['nt', 'ax', 'lqparen', 'EOF', 't', 'rqparen', ]
nterms = ["Symbol", "Expr", "Rule", "AxDecl", "Rules'", "Rules", "S", "Prod", "Prods'", "Prods", ]
predict_table = {
    'Symbol': {
        'nt': ['nt'],
        'ax': ['ERROR'],
        'lqparen': ['ERROR'],
        'EOF': ['ERROR'],
        't': ['t'],
        'rqparen': ['ERROR'],
    },
    'Expr': {
        'nt': ['Symbol', 'Expr'],
        'ax': ['ERROR'],
        'lqparen': ['ERROR'],
        'EOF': ['ERROR'],
        't': ['Symbol', 'Expr'],
        'rqparen': ['ε'],
    },
    'Rule': {
        'nt': ['ERROR'],
        'ax': ['ERROR'],
        'lqparen': ['lqparen', 'nt', 'Prods', 'rqparen'],
        'EOF': ['ERROR'],
        't': ['ERROR'],
        'rqparen': ['ERROR'],
    },
    'AxDecl': {
        'nt': ['ERROR'],
        'ax': ['ERROR'],
        'lqparen': ['lqparen', 'ax', 'lqparen', 'nt', 'rqparen', 'rqparen'],
        'EOF': ['ERROR'],
        't': ['ERROR'],
        'rqparen': ['ERROR'],
    },
    "Rules'": {
        'nt': ['ERROR'],
        'ax': ['ERROR'],
        'lqparen': ['Rule', "Rules'"],
        'EOF': ['ε'],
        't': ['ERROR'],
        'rqparen': ['ERROR'],
    },
    'Rules': {
        'nt': ['ERROR'],
        'ax': ['ERROR'],
        'lqparen': ['Rule', "Rules'"],
        'EOF': ['ERROR'],
        't': ['ERROR'],
        'rqparen': ['ERROR'],
    },
    'S': {
        'nt': ['ERROR'],
        'ax': ['ERROR'],
        'lqparen': ['AxDecl', 'Rules'],
        'EOF': ['ERROR'],
        't': ['ERROR'],
        'rqparen': ['ERROR'],
    },
    'Prod': {
        'nt': ['ERROR'],
        'ax': ['ERROR'],
        'lqparen': ['lqparen', 'Expr', 'rqparen'],
        'EOF': ['ERROR'],
        't': ['ERROR'],
        'rqparen': ['ERROR'],
    },
    "Prods'": {
        'nt': ['ERROR'],
        'ax': ['ERROR'],
        'lqparen': ['Prod', "Prods'"],
        'EOF': ['ERROR'],
        't': ['ERROR'],
        'rqparen': ['ε'],
    },
    'Prods': {
        'nt': ['ERROR'],
        'ax': ['ERROR'],
        'lqparen': ['Prod', "Prods'"],
        'EOF': ['ERROR'],
        't': ['ERROR'],
        'rqparen': ['ERROR'],
    },
}
