(define (read-words)
  (let loop ((string ""))
    (if (eof-object? (peek-char))
        (if (not (equal? string ""))
        (cons string '())
        '())
        (if (not (or (equal? #\space (peek-char)) (equal? #\newline (peek-char))))
            (loop (string-append string (list->string (list (read-char)))))
            (begin
              (let loop2 ()
                (read-char)
                (if (eof-object? (peek-char))
                    (if (not (equal? string ""))
                        (cons string (loop ""))
                        (loop ""))
                    (if (or (equal? #\space (peek-char)) (equal? #\newline (peek-char)))
                        (loop2)
                        (if (not (equal? string ""))
                            (cons string (loop ""))
                            (loop ""))))))))))
