(define (ref posled . xs)
  (if (= (length xs) 1)
      (if (list? posled)
          (and (< (car xs) (length posled))
               (list-ref posled (car xs)))  
          (if (vector? posled)
              (and (< (car xs) (length (vector->list posled)))
                   (vector-ref posled (car xs)))  
              (if (string? posled)
                  (and (< (car xs) (length (string->list posled)))
                       (string-ref posled (car xs))))))    
      (if (list? posled)
          (and (or (< (car xs) (length posled)) (= (car xs) (length posled)))                        
               (if (or (null? posled) (= (car xs) 0))
                   (cons (cadr xs) posled)
                   (cons (car posled)
                         (ref (cdr posled) (- (car xs) 1) (cadr xs)))))  
          (if (vector? posled)
              (and (or (< (car xs) (length (vector->list posled)))
                       (= (car xs) (length (vector->list posled))))
                   (list->vector
                    (if (or (null? posled) (= (car xs) 0))
                        (cons (cadr xs) (vector->list posled))
                        (cons (car (vector->list posled))
                              (ref (cdr (vector->list posled)) (- (car xs) 1) (cadr xs))))))  
              (if (string? posled)
                  (and (and (or (< (car xs)
                                   (length (string->list posled)))
                                (= (car xs) (length (string->list posled))))
                            (not (number? (cadr xs)))
                            (not (symbol? (cadr xs))))
                       (if (or (null? posled) (= (car xs) 0))
                           (list->string (append (string->list (string (cadr xs))) (string->list posled)))
                           (list->string (cons (car (string->list posled))
                                               (string->list (ref (list->string
                                                                   (cdr (string->list posled)))
                                                                  (- (car xs) 1) (cadr xs))))))))))))  
