[tool.poetry]
name = "lab5"
version = "0.1.0"
description = ""
authors = ["RELICT <pigift@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.3"
ruff = "^0.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
